// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1788364044);
user_pref("app.update.lastUpdateTime.background-update-timer", 1788364044);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1788364044);
user_pref("app.update.lastUpdateTime.glean-addons-daily", 1788364044);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1788364044);
user_pref("app.update.lastUpdateTime.region-update-timer", 1788364044);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1788364044);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1788364044);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1788364044);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "1689f909-3ddf-498e-b9c5-ad33e5439c68");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1788364016);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 177);
user_pref("browser.newtabpage.activity-stream.impressionId", "{604f27a3-30fc-43fb-b6ac-089633b5fe4f}");
user_pref("browser.newtabpage.activity-stream.newtabWallpapers.user.enabled.migrated", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.preonboarding.splashShown", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1788364016730");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1788385616730");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1788364075");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1788364018);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\",\"ai-window-toggle\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"reset-pbm-toolbar-button\",\"ai-window-toggle\",\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\"],\"currentVersion\":25,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 7);
user_pref("captchadetection.lastSubmission", 1788364);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "78783b41-9cb5-4111-802f-c7aa5cbba8e2");
user_pref("datareporting.dau.cachedUsageProfileID", "27dece56-75d6-493e-9ebb-84cd16cd469d");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1788364075915");
user_pref("distribution.iniFile.exists.appversion", "154.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint-001.bookmarksProcessed", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-CA@firefox.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-en-GB@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20260824154132");
user_pref("extensions.lastAppVersion", "154.0.1");
user_pref("extensions.lastPlatformVersion", "154.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"c64ac987-bf36-44d2-846c-f83ea7af5af4\",\"ipp-activator@mozilla.com\":\"28ab0a57-6cbf-4e21-9048-08925b4e5be4\",\"pictureinpicture@mozilla.org\":\"46e6f0a5-d11b-4bbd-a5c8-665fc94f05e1\",\"addons-search-detection@mozilla.com\":\"a280ef29-88df-4bc1-8192-3c7c27b1d5f4\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"b0ff12a1-e1f9-4039-bc0c-8544b52919f7\",\"default-theme@mozilla.org\":\"ed2be27a-72cd-4de1-9a32-002b0542d538\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: 2153398257, errorCode: 2, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1788364035);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1788364035);
user_pref("media.gmp-manager.buildID", "20260824154132");
user_pref("media.gmp-manager.lastCheck", 1788364035);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.firstUpdateComplete", true);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 5);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "53ec38e1-bb6e-4e52-b09d-0c17d83aca68");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("privacy.trackingprotection.allow_list.hasUserInteractedWithETPSettings", true);
user_pref("security.pki.mitm_canary_issuer", "CN=antigravity CA");
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.visibility", "hide-on-close");
user_pref("signon.storage.rust.restoreDone", true);
user_pref("toolkit.profiles.storeID", "8764dc2c");
user_pref("toolkit.startup.last_success", 1788364010);
user_pref("toolkit.telemetry.cachedClientID", "0961987c-f3bc-48f2-a9e1-8b37c40a94a5");
user_pref("toolkit.telemetry.cachedProfileGroupID", "05340b89-7fbd-44b8-9192-3572402adc3d");
user_pref("toolkit.telemetry.previousBuildID", "20260824154132");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
